version: '2.1'
services:

    postgres:
        image: postgres:11
        ports:
            - ${PG_PORT-5432}:5432
        environment:
            POSTGRES_USER: ${PG_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
            POSTGRES_DB: ${PG_DATABASE:-postgres}
        volumes:
            - ${HUMBLE_DATA:-./data}/pg-dev:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP:-./data/backup}:/backup
        restart: always

    webapp:
        image: node:12.2-alpine
        ports:
            - ${WEBAPP_API_PORT:-8080}:8080
            - ${WEBAPP_CRA_PORT:-3000}:3000
        volumes:
            - ${HUMBLE_DATA:-./data}/webapp/node_modules:/usr/src/app/node_modules:cached
            - ${HUMBLE_DATA:-./data}/webapp/node_build:/usr/src/app/node_build:cached
            - ./services/webapp/package.json:/usr/src/app/package.json:delegated
            - ./services/webapp/yarn.lock:/usr/src/app/yarn.lock:delegated
            - ./services/webapp/jsconfig.json:/usr/src/app/jsconfig.json:delegated
            - ./services/webapp/src:/usr/src/app/src:delegated
            - ./services/webapp/ssr:/usr/src/app/ssr:delegated
            - ./services/webapp/public:/usr/src/app/public:delegated
            - ./services/webapp/index.js:/usr/src/app/index.js:delegated
            - ./services/webapp/.env:/usr/src/app/.env:delegated
        environment:
            REACT_APP_ID: ${REACT_APP_ID}
            REACT_APP_NAME: ${REACT_APP_NAME}
            PG_HOST: postgres
            PG_PORT: 5432
            PG_USERNAME: ${PG_USERNAME:-postgres}
            PG_PASSWORD: ${PG_PASSWORD:-postgres}
            PG_DATABASE: ${PG_DATABASE:-postgres}
            JWT_SECRET: ${JWT_SECRET:-xxx}
            JWT_DURATION: ${JWT_DURATION:-1y}
            HASH_ROUNDS: ${HASH_ROUNDS:-5}
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev" ]

    styleguide:
        image: node:12.2-alpine
        ports:
            - ${WEBAPP_STYLEGUIDE_PORT:-6060}:6060
        volumes:
            - ${HUMBLE_DATA:-./data}/webapp/node_modules:/usr/src/app/node_modules:cached
            - ./services/webapp/package.json:/usr/src/app/package.json:delegated
            - ./services/webapp/yarn.lock:/usr/src/app/yarn.lock:delegated
            - ./services/webapp/jsconfig.json:/usr/src/app/jsconfig.json:delegated
            - ./services/webapp/styleguide.config.js:/usr/src/app/styleguide.config.js:delegated
            - ./services/webapp/webpack.config.extend.js:/usr/src/app/webpack.config.extend.js:delegated
            - ./services/webapp/src:/usr/src/app/src:delegated
            - ./services/webapp/public:/usr/src/app/public:delegated
            - ./services/webapp/index.js:/usr/src/app/index.js:delegated
        environment:
            REACT_APP_ID: ${REACT_APP_ID}
            REACT_APP_NAME: ${REACT_APP_NAME}
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "styleguide" ]
